// Generated by listennotes/devtools/api-sdks/sync.py scala. Do not edit.
package podcast.api.scala.demo

import com.listennotes.podcast_api.Client
import com.listennotes.podcast_api.ApiResponse

object GeneratedExamples {
    def search(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("q", "star wars")
        parameters.put("sort_by_date", "0")
        parameters.put("type", "episode")
        parameters.put("offset", "0")
        parameters.put("len_min", "10")
        parameters.put("len_max", "30")
        parameters.put("genre_ids", "68,82")
        parameters.put("published_before", "1580172454000")
        parameters.put("published_after", "0")
        parameters.put("only_in", "title,description")
        parameters.put("language", "English")
        parameters.put("region", "")
        parameters.put("safe_mode", "0")
        parameters.put("unique_podcasts", "0")
        parameters.put("interviews_only", "0")
        parameters.put("sponsored_only", "0")
        parameters.put("page_size", "10")
        client.search(parameters)
    }

    def typeahead(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("q", "star wars")
        parameters.put("show_podcasts", "1")
        parameters.put("show_genres", "1")
        parameters.put("safe_mode", "0")
        client.typeahead(parameters)
    }

    def searchEpisodeTitles(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("q", "Jerusalem Demsas on The Dispossessed")
        client.searchEpisodeTitles(parameters)
    }

    def spellcheck(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("q", "microsft stock")
        client.spellcheck(parameters)
    }

    def getRelatedSearches(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("q", "evergrande")
        client.fetchRelatedSearches(parameters)
    }

    def getTrendingSearches(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        client.fetchTrendingSearches(parameters)
    }

    def getBestPodcasts(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("genre_id", "93")
        parameters.put("page", "2")
        parameters.put("region", "us")
        parameters.put("sort", "listen_score")
        parameters.put("safe_mode", "0")
        client.fetchBestPodcasts(parameters)
    }

    def getPodcastById(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("id", "4d3fe717742d4963a85562e9f84d8c79")
        parameters.put("next_episode_pub_date", "1479154463000")
        parameters.put("sort", "recent_first")
        client.fetchPodcastById(parameters)
    }

    def deletePodcastById(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("id", "4d3fe717742d4963a85562e9f84d8c79")
        parameters.put("reason", "the podcaster wants to delete it")
        client.deletePodcast(parameters)
    }

    def getEpisodeById(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("id", "6b6d65930c5a4f71b254465871fed370")
        parameters.put("show_transcript", "1")
        client.fetchEpisodeById(parameters)
    }

    def getEpisodesInBatch(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("ids", "c577d55b2b2b483c969fae3ceb58e362,0f34a9099579490993eec9e8c8cebb82")
        client.batchFetchEpisodes(parameters)
    }

    def getPodcastsInBatch(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("ids", "3302bc71139541baa46ecb27dbf6071a,68faf62be97149c280ebcc25178aa731,37589a3e121e40debe4cef3d9638932a,9cf19c590ff0484d97b18b329fed0c6a")
        parameters.put("rsses", "https://rss.art19.com/recode-decode,https://rss.art19.com/the-daily,https://www.npr.org/rss/podcast.php?id=510331,https://www.npr.org/rss/podcast.php?id=510331")
        parameters.put("itunes_ids", "1457514703,1386234384,659155419")
        parameters.put("spotify_ids", "3DDfEsKDIDrTlnPOiG4ZF4,4qDNe5Gvl1XxdLinUGEXrC,23NZCM4ik6o3UYkM473Itz")
        parameters.put("show_latest_episodes", "1")
        parameters.put("next_episode_pub_date", "1557394247000")
        client.batchFetchPodcasts(parameters)
    }

    def getCuratedPodcastById(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("id", "SDFKduyJ47r")
        client.fetchCuratedPodcastsListById(parameters)
    }

    def getGenres(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("top_level_only", "1")
        client.fetchPodcastGenres(parameters)
    }

    def getRegions(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        client.fetchPodcastRegions(parameters)
    }

    def getLanguages(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        client.fetchPodcastLanguages(parameters)
    }

    def justListen(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        client.justListen(parameters)
    }

    def getCuratedPodcasts(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("page", "2")
        client.fetchCuratedPodcastsLists(parameters)
    }

    def getPodcastRecommendations(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("id", "25212ac3c53240a880dd5032e547047b")
        parameters.put("safe_mode", "0")
        client.fetchRecommendationsForPodcast(parameters)
    }

    def getEpisodeRecommendations(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("id", "254444fa6cf64a43a95292a70eb6869b")
        parameters.put("safe_mode", "0")
        client.fetchRecommendationsForEpisode(parameters)
    }

    def submitPodcast(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("rss", "https://feeds.megaphone.fm/committed")
        parameters.put("email", "hello@example.com")
        client.submitPodcast(parameters)
    }

    def getPlaylistById(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("id", "m1pe7z60bsw")
        parameters.put("type", "episode_list")
        parameters.put("last_timestamp_ms", "0")
        parameters.put("sort", "recent_added_first")
        client.fetchPlaylistById(parameters)
    }

    def getPlaylists(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("sort", "recent_added_first")
        parameters.put("page", "1")
        client.fetchMyPlaylists(parameters)
    }

    def getPodcastAudience(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("id", "25212ac3c53240a880dd5032e547047b")
        client.fetchAudienceForPodcast(parameters)
    }

    def getPodcastsByDomainName(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("domain_name", "nytimes.com")
        parameters.put("page", "1")
        client.fetchPodcastsByDomain(parameters)
    }

    def createPlaylist(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("name", "My favorite podcasts")
        parameters.put("description", "Podcasts and episodes to revisit.")
        parameters.put("visibility", "public")
        parameters.put("type", "episode_list")
        client.createPlaylist(parameters)
    }

    def updatePlaylist(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("id", "m1pe7z60bsw")
        parameters.put("name", "My favorite podcasts")
        parameters.put("description", "Podcasts and episodes to revisit.")
        parameters.put("visibility", "public")
        parameters.put("type", "podcast_list")
        client.updatePlaylist(parameters)
    }

    def deletePlaylist(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("id", "m1pe7z60bsw")
        client.deletePlaylist(parameters)
    }

    def addPlaylistItem(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("id", "m1pe7z60bsw")
        parameters.put("episode_id", "e53e6992a5b7492f9ea6fcd85d9ad95f")
        parameters.put("notes", "Worth a listen.")
        client.addPlaylistItem(parameters)
    }

    def deletePlaylistItem(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("id", "m1pe7z60bsw")
        parameters.put("item_id", "23")
        client.deletePlaylistItem(parameters)
    }

    def updatePlaylistItemNotes(client: Client): ApiResponse = {
        val parameters = new java.util.HashMap[String, String]()
        parameters.put("id", "m1pe7z60bsw")
        parameters.put("item_id", "23")
        parameters.put("notes", "")
        client.updatePlaylistItemNotes(parameters)
    }

    def call(client: Client, operation: String, parameters: java.util.Map[String, String]): ApiResponse =
        operation match {
            case "search" => client.search(parameters)
            case "typeahead" => client.typeahead(parameters)
            case "searchEpisodeTitles" => client.searchEpisodeTitles(parameters)
            case "spellcheck" => client.spellcheck(parameters)
            case "getRelatedSearches" => client.fetchRelatedSearches(parameters)
            case "getTrendingSearches" => client.fetchTrendingSearches(parameters)
            case "getBestPodcasts" => client.fetchBestPodcasts(parameters)
            case "getPodcastById" => client.fetchPodcastById(parameters)
            case "deletePodcastById" => client.deletePodcast(parameters)
            case "getEpisodeById" => client.fetchEpisodeById(parameters)
            case "getEpisodesInBatch" => client.batchFetchEpisodes(parameters)
            case "getPodcastsInBatch" => client.batchFetchPodcasts(parameters)
            case "getCuratedPodcastById" => client.fetchCuratedPodcastsListById(parameters)
            case "getGenres" => client.fetchPodcastGenres(parameters)
            case "getRegions" => client.fetchPodcastRegions(parameters)
            case "getLanguages" => client.fetchPodcastLanguages(parameters)
            case "justListen" => client.justListen(parameters)
            case "getCuratedPodcasts" => client.fetchCuratedPodcastsLists(parameters)
            case "getPodcastRecommendations" => client.fetchRecommendationsForPodcast(parameters)
            case "getEpisodeRecommendations" => client.fetchRecommendationsForEpisode(parameters)
            case "submitPodcast" => client.submitPodcast(parameters)
            case "getPlaylistById" => client.fetchPlaylistById(parameters)
            case "getPlaylists" => client.fetchMyPlaylists(parameters)
            case "getPodcastAudience" => client.fetchAudienceForPodcast(parameters)
            case "getPodcastsByDomainName" => client.fetchPodcastsByDomain(parameters)
            case "createPlaylist" => client.createPlaylist(parameters)
            case "updatePlaylist" => client.updatePlaylist(parameters)
            case "deletePlaylist" => client.deletePlaylist(parameters)
            case "addPlaylistItem" => client.addPlaylistItem(parameters)
            case "deletePlaylistItem" => client.deletePlaylistItem(parameters)
            case "updatePlaylistItemNotes" => client.updatePlaylistItemNotes(parameters)
            case _ => throw new IllegalArgumentException("Unknown operation: " + operation)
        }
}
